name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Backend Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/projectposts-backend:${{ github.sha }} ./backend

      - name: Push Backend Docker Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/projectposts-backend:${{ github.sha }}

      - name: Build Frontend Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/projectposts-frontend:${{ github.sha }} ./frontend

      - name: Push Frontend Docker Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/projectposts-frontend:${{ github.sha }}

      - name: Run Tests
        run: |
          # Здесь должны быть команды для запуска ваших тестов
          # Например: docker run projectposts-backend:${{ github.sha }} test

      - name: Deploy to Remote Server
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Удаление старых образов и контейнеров
            docker pull ghcr.io/${{ github.repository_owner }}/projectposts-backend:${{ github.sha }}
            docker stop myapp-backend-container || true
            docker rm myapp-backend-container || true
            docker rmi $(docker images -q ghcr.io/${{ github.repository_owner }}/projectposts-backend:previous) || true
            docker tag ghcr.io/${{ github.repository_owner }}/projectposts-backend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/projectposts-backend:previous
            docker run -d --name myapp-backend-container -p 80:3006 ghcr.io/${{ github.repository_owner }}/projectposts-backend:${{ github.sha }}
            
            docker pull ghcr.io/${{ github.repository_owner }}/projectposts-frontend:${{ github.sha }}
            docker stop myapp-frontend-container || true
            docker rm myapp-frontend-container || true
            docker rmi $(docker images -q ghcr.io/${{ github.repository_owner }}/projectposts-frontend:previous) || true
            docker tag ghcr.io/${{ github.repository_owner }}/projectposts-frontend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/projectposts-frontend:previous
            docker run -d --name myapp-frontend-container -p 8081:80 ghcr.io/${{ github.repository_owner }}/projectposts-frontend:${{ github.sha }}

            # Очистка неиспользуемых образов
            docker image prune -af